### ISSUE TITLE
Access denied to WIDER_train_dataset_url and WIDER_train_face_annotations_url

### ISSUE THREAD

**Issue by anirudhbhat1999** [VladKha/object_detector#2]
Kindly provide the access to WIDER_train_face_annotations_url and WIDER_train_dataset_url

**Comment by VladKha** [comment]
@anirudhbhat1999, thank you for reaching out, please check the https://github.com/VladKha/object_detector/blob/master/bin/test_object_detector.py file
Hope this helps

**Comment by anirudhbhat1999** [comment]
@VladKha Have checked it. But the access is still denied.

**Comment by VladKha** [comment]
@anirudhbhat1999, probably Google download links are already obsolete, check the originals Google Drive links in `Download` section of http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/
If you're denied access to this URL as well, probably you need to try using VPN

**Comment by anirudhbhat1999** [comment]
@VladKha Google drive link is opening. No issues, Thank you.
